credentials:
  usernames:
    ssasaki:
      email: samuel.sasaki@gmail.com
      name: Samuel Sasaki
      password: $2b$12$iA/tkVPYjP3iyTltBDEt1.xQgrvnoA.QJ9aKJC97oqGg2atRls5qO # To be replaced with hashed password
      api_key: ''
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$0Q.UROCSbkp24m2Dfn5Pdezo8/56HzGvrOIcc7XCPjZ/z2BiTuAmy # To be replaced with hashed password
      api_key: ''
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
